apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- application
- pipeline
- metadata
- cache
- cache-deployer
- tekton

resources:
  - pipeline-application.yaml

images:
  - name: gcr.io/ml-pipeline/api-server
    newName: docker.io/aipipeline/api-server
    newTag: latest
  - name: gcr.io/ml-pipeline/persistenceagent
    newName: docker.io/aipipeline/persistenceagent
    newTag: latest
  - name: gcr.io/ml-pipeline/frontend
    newName: docker.io/aipipeline/frontend
    newTag: latest
  - name: gcr.io/ml-pipeline/metadata-writer
    newName: docker.io/aipipeline/metadata-writer
    newTag: latest
  - name: gcr.io/ml-pipeline/scheduledworkflow
    newName: docker.io/aipipeline/scheduledworkflow
    newTag: latest

# Used by Kustomize
configMapGenerator:
- name: pipeline-install-config
  env: params.env
secretGenerator:
- name: mysql-secret
  env: params-db-secret.env
vars:
- name: kfp-namespace
  objref:
    kind: Deployment
    apiVersion: apps/v1
    name: ml-pipeline
  fieldref:
    fieldpath: metadata.namespace
- name: kfp-app-name
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appName
- name: kfp-app-version
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appVersion
- name: kfp-artifact-bucket-name
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.bucketName
- name: kfp-container-runtime-executor
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.containerRuntimeExecutor
configurations:
- params.yaml
