matrix:
  include:
    - name: "Unit tests, Python 3.6"
      language: python
      python: "3.6"
      env: TOXENV=py36
      install:
        - python3 -m pip install -e sdk/python
      script:
        - make test
    - name: "Unit tests, Python 3.7"
      language: python
      python: "3.7"
      env: TOXENV=py37
      install:
        - python3 -m pip install -e sdk/python
      script:
        - make test
    - name: "Progress report on compiling KFP DSL test scripts"
      language: python
      python: "3.7"
      install:
        - python3 -m pip install -e sdk/python
      script:
        - make report
    - name: "Verify source files contain the license header"
      language: bash
      script:
        - make check_license
    - name: "Lint Python code with flake8"
      language: python
      python: "3.7"
      install:
        - pip install flake8
      script:
        - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
